// Regenerate with: dart run tool/ffigen.dart

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:postgresql_parser/src/native/pg18.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Void Function(ffi.Pointer<Pg18ParseResponse>)>()
external void pgp18_free_response(ffi.Pointer<Pg18ParseResponse> response);

@ffi.Native<ffi.Pointer<Pg18ParseResponse> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<Pg18ParseResponse> pgp18_parse(ffi.Pointer<ffi.Char> sql);

@ffi.Native<ffi.Pointer<Pg18ParseResponse> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<Pg18ParseResponse> pgp18_parse_plpgsql(
  ffi.Pointer<ffi.Char> sql,
);

final class Pg18ParseResponse extends ffi.Struct {
  external ffi.Pointer<ffi.Char> tree_json;

  external ffi.Pointer<ffi.Char> error_message;

  @ffi.Int()
  external int cursor_position;

  static ffi.Pointer<Pg18ParseResponse> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> tree_json,
    required ffi.Pointer<ffi.Char> error_message,
    required int cursor_position,
  }) => $allocator<Pg18ParseResponse>()
    ..ref.tree_json = tree_json
    ..ref.error_message = error_message
    ..ref.cursor_position = cursor_position;
}
